# 1 Test DataLoader understanding

In [32]:
import torch
torch.manual_seed(23)
from torch import nn

In [33]:
context_len = 32
hidden_d =   8
vocab_size = 10

In [34]:
??nn.Embedding

Init signature:
nn.Embedding(
    num_embeddings: int,
    embedding_dim: int,
    padding_idx: int | None = None,
    max_norm: float | None = None,
    norm_type: float = 2.0,
    scale_grad_by_freq: bool = False,
    sparse: bool = False,
    _weight: torch.Tensor | None = None,
    _freeze: bool = False,
    device=None,
    dtype=None,
) -> None
Source:        
class Embedding(Module):
    r"""A simple lookup table that stores embeddings of a fixed dictionary and size.

    This module is often used to store word embeddings and retrieve them using indices.
    The input to the module is a list of indices, and the output is the corresponding
    word embeddings.

    Args:
        num_embeddings (int): size of the dictionary of embeddings
        embedding_dim (int): the size of each embedding vector
        padding_idx (int, optional): If specified, the entries at :attr:`padding_idx` do not contribute to the gradient;
                                     therefore, the embedding v

In [35]:
embedding = nn.Embedding(vocab_size,hidden_d)
linear = nn.Linear(vocab_size,hidden_d)

In [36]:
embedding.weight.shape , linear.weight.shape

(torch.Size([10, 8]), torch.Size([8, 10]))

In [37]:
linear.weight = nn.Parameter(embedding.weight.T)

In [38]:
idx = torch.tensor([2, 9, 1])
onehot = nn.functional.one_hot(idx)

In [39]:
onehot

tensor([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [40]:
embedding(idx)

tensor([[-0.6774,  0.8949,  0.9096,  0.4260,  1.2886, -0.1708, -0.8564, -0.6576],
        [-1.1796, -1.0491, -1.0066, -0.4865,  0.1088, -1.0973,  1.9052,  0.3173],
        [-0.5531,  0.6016, -0.9271,  0.5655, -2.4451, -0.1605,  0.1804,  2.2347]],
       grad_fn=<EmbeddingBackward0>)

In [41]:
linear(onehot.float())

tensor([[-0.7143,  0.7057,  0.8223,  0.5984,  1.4391, -0.2464, -0.8934, -0.8332],
        [-1.2165, -1.2383, -1.0938, -0.3141,  0.2592, -1.1729,  1.8682,  0.1417],
        [-0.5900,  0.4124, -1.0143,  0.7379, -2.2947, -0.2361,  0.1435,  2.0591]],
       grad_fn=<AddmmBackward0>)

In [42]:
onehot.float()

tensor([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
embedding.weight

Parameter containing:
tensor([[-0.9012,  0.5656, -0.4882,  0.7507,  0.5893, -0.4552, -0.8135,  0.2670],
        [-0.5531,  0.6016, -0.9271,  0.5655, -2.4451, -0.1605,  0.1804,  2.2347],
        [-0.6774,  0.8949,  0.9096,  0.4260,  1.2886, -0.1708, -0.8564, -0.6576],
        [-0.2041,  0.1203, -0.6191, -0.6317, -0.5774,  0.5874,  0.1230,  0.0885],
        [-0.8708,  1.3073, -0.4785,  0.1740, -0.2219, -0.4277,  1.0395, -1.5168],
        [-0.2913,  0.7265,  1.3873, -0.6213,  1.0785, -0.1966,  1.1847,  0.8043],
        [-0.3349, -0.0659, -0.1244, -0.8531,  1.2268, -2.0151,  0.1955, -1.5921],
        [-0.5662,  0.4007, -0.7016,  0.1341,  1.9434,  1.0825, -1.5422,  0.6945],
        [ 0.2914, -0.9938,  1.1093, -0.1230, -0.6921,  1.2534, -0.3842, -0.8658],
        [-1.1796, -1.0491, -1.0066, -0.4865,  0.1088, -1.0973,  1.9052,  0.3173]],
       requires_grad=True)

In [45]:
linear.weight.T

tensor([[-0.9012,  0.5656, -0.4882,  0.7507,  0.5893, -0.4552, -0.8135,  0.2670],
        [-0.5531,  0.6016, -0.9271,  0.5655, -2.4451, -0.1605,  0.1804,  2.2347],
        [-0.6774,  0.8949,  0.9096,  0.4260,  1.2886, -0.1708, -0.8564, -0.6576],
        [-0.2041,  0.1203, -0.6191, -0.6317, -0.5774,  0.5874,  0.1230,  0.0885],
        [-0.8708,  1.3073, -0.4785,  0.1740, -0.2219, -0.4277,  1.0395, -1.5168],
        [-0.2913,  0.7265,  1.3873, -0.6213,  1.0785, -0.1966,  1.1847,  0.8043],
        [-0.3349, -0.0659, -0.1244, -0.8531,  1.2268, -2.0151,  0.1955, -1.5921],
        [-0.5662,  0.4007, -0.7016,  0.1341,  1.9434,  1.0825, -1.5422,  0.6945],
        [ 0.2914, -0.9938,  1.1093, -0.1230, -0.6921,  1.2534, -0.3842, -0.8658],
        [-1.1796, -1.0491, -1.0066, -0.4865,  0.1088, -1.0973,  1.9052,  0.3173]],
       grad_fn=<PermuteBackward0>)